import { ArrowUpRight, BookOpen } from "lucide-react";

const papers = [
  { tag: "ITiCSE 2026 · Published", title: "Caliber: AI-Assisted Infrastructure for Mastery-Based Computer Science Education at Scale", authors: "Nikhil Kapasi, Derek Kirschbaum, Aryaman Singh, Diba Mirza", description: "Our platform for connecting course content, AI-assisted assessment, and mastery-oriented learning in computer science.", url: "https://doi.org/10.1145/3803401.3811974", link: "Read the ACM paper" },
  { tag: "ITiCSE 2026 · Published", title: "Designing Scalable, Context-Adapted CS Placement Exams: An IRT-Based Approach", authors: "Nikhil Kapasi, Sai Vamsi Alisetti, Cindy Zhao, Diba Mirza", description: "Research on placement assessment adapted to course context and designed to work at scale.", url: "https://iticse.acm.org/2026/program/", link: "View the conference program" },
  { tag: "ITiCSE 2026 · Published", title: "Bridging Academia and Industry: A Structured Model for Running a Successful Computer Engineering Capstone Program", authors: "Yogananda Isukapalli, Nikhil Kapasi", description: "A structured approach to industry-partnered computer engineering capstone education.", url: "https://doi.org/10.1145/3803401.3812006", link: "Read the ACM paper" },
];

export default function ResearchPage() {
  return <div className="min-h-screen bg-[#f7f5ed] text-[#123146]"><section className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="mb-16 max-w-3xl"><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#23747a]"><BookOpen size={17}/> Research at Caliber</div><h1 className="text-5xl font-bold tracking-tight md:text-7xl">Ideas tested in real classrooms.</h1><p className="mt-6 text-lg leading-8 text-[#5b7073]">Explore publications by Caliber team lead Nikhil Kapasi: computing education research connected to our platform, plus related work in engineering education.</p></div><div className="grid gap-5">{papers.map(p=><article key={p.title} className="rounded-xl border border-[#dce7de] bg-white p-7 md:p-10"><span className="text-xs font-bold uppercase tracking-[.14em] text-[#28747b]">{p.tag}</span><h2 className="mt-5 max-w-4xl text-2xl font-bold leading-tight md:text-3xl">{p.title}</h2><p className="mt-3 text-sm font-medium text-[#536b70]">{p.authors}</p><p className="mt-5 max-w-3xl leading-7 text-[#5b7073]">{p.description}</p><a href={p.url} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 border-b border-[#176c75] pb-1 font-bold text-[#176c75]">{p.link}<ArrowUpRight size={17}/></a></article>)}</div><p className="mt-8 text-sm text-[#718682]">Selected publications by Nikhil Kapasi. Publication links and venue details are provided with each work.</p></section></div>
}
