"use client";

import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Network, MessageCircle, ClipboardCheck } from "lucide-react";

const workflows = [
  { icon: Network, name: "Course intelligence", heading: "Give every question context.", text: "Connect learning outcomes to the material students have actually seen. Course mapping gives content generation and review a shared foundation.", chips: ["Concept mapping", "Course materials", "Question generation"], evidence: "Caliber: AI-Assisted Infrastructure for Mastery-Based Computer Science Education at Scale", href: "https://doi.org/10.1145/3803401.3811974", visual: ["Course materials", "Concept relationships", "Aligned practice"] },
  { icon: ClipboardCheck, name: "Better assessment", heading: "Make assessment more informative.", text: "Our placement exam research asks how assessments can work at scale while reflecting a course’s local context. That question informs how we think about evidence of understanding.", chips: ["Placement exams", "Item response theory", "Course context"], evidence: "Designing Scalable, Context-Adapted CS Placement Exams: An IRT-Based Approach", href: "https://iticse.acm.org/2026/program/", visual: ["Assessment design", "Student responses", "Placement insight"] },
  { icon: MessageCircle, name: "Student support", heading: "Keep the next step within reach.", text: "We are building course-aware explanations, practice, and feedback into the student experience—so help stays connected to what the class is learning.", chips: ["Guided explanations", "Targeted practice", "Feedback"], evidence: "Explore the Caliber platform and course collaborations", href: "/product", visual: ["A student question", "Course-aware support", "A next step"] },
];
export function WorkflowExplorer(){const [active,setActive]=useState(0);const reduced=useReducedMotion();const item=workflows[active];return <section className="workflow-section"><div className="home-shell"><div className="section-top"><div><div className="section-kicker">INSIDE CALIBER</div><h2>Real classroom problems.<br/>New possibilities.</h2></div><p>Explore how the platform connects to the questions driving our research.</p></div><div className="workflow-tabs" role="tablist" aria-label="Explore Caliber workflows">{workflows.map(({icon:Icon,name},i)=><button key={name} id={`workflow-tab-${i}`} role="tab" aria-selected={active===i} aria-controls="workflow-panel" tabIndex={active===i?0:-1} onKeyDown={event=>{if(["ArrowRight","ArrowLeft","Home","End"].includes(event.key)){event.preventDefault();const next=event.key==="Home"?0:event.key==="End"?2:(active+(event.key==="ArrowRight"?1:2))%3;setActive(next);document.getElementById(`workflow-tab-${next}`)?.focus();}}} onClick={()=>setActive(i)}><Icon size={18}/>{name}</button>)}</div><div id="workflow-panel" role="tabpanel" aria-labelledby={`workflow-tab-${active}`} tabIndex={0} className="workflow-panel"><AnimatePresence mode="wait"><motion.div key={active} className="workflow-content" initial={{opacity:reduced?1:0,y:reduced?0:10}} animate={{opacity:1,y:0}} exit={{opacity:reduced?1:0}} transition={{duration:.2}}><div><h3>{item.heading}</h3><p>{item.text}</p><div className="demo-tags">{item.chips.map(chip=><span key={chip}>{chip}</span>)}</div><Link className="workflow-evidence" href={item.href}>{item.evidence}<ArrowUpRight size={20}/></Link></div><div className="workflow-steps">{item.visual.map((step,i)=><div key={step}><span>0{i+1}</span><strong>{step}</strong><span className="step-signal"/></div>)}</div></motion.div></AnimatePresence></div></div></section>}
